apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansiblerunners.app.example.com
spec:
  group: app.example.com
  names:
    kind: AnsibleRunner
    listKind: AnsibleRunnerList
    plural: ansiblerunners
    singular: ansiblerunner
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: AnsibleRunner is the Schema for the ansiblerunners API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AnsibleRunnerSpec defines the desired state of AnsibleRunner
            type: object
          status:
            description: AnsibleRunnerStatus defines the observed state of AnsibleRunner
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
